### ISSUE TITLE
Partition Metrics

### ISSUE THREAD

**Issue by goldmerc** [saintsystems/nova-linkable-metrics#27]
I'm trying to understand what this package does in the context of Partition Metrics? If a partition metric has 5 different partitions, does it allow you to add a different link to each partition? Or is it just one link for the whole card?

For instance, let's say your Partition Metric shows the status for products - "For Sale", "Sold", "Reserved". And I want each partition to link to the products resource page and filter by the status. Can I do that with this package?

Thanks!

**Comment by anderly** [comment]
@goldmerc,

Currently, it's just one link for the whole card. However, we're open to a PR to allow your use case.

**Comment by jonnywilliamson** [comment]
Yeah that's exactly what I came for here too!! Thought I had struck gold initially!

**Comment by vesper8** [comment]
For anyone interested, I've wanted to have clickable items in a partition metric for a long time and I just spent a few hours forking this package and adding this functionality. The way I did it is a bit hacky, but in the end it's super easy.

If you use my latest fork you can now do something like this:

```

        $result = $this->result($top);

        $result->partitionLabelLinkMap($partitionLabelLinkMap);

        return $result;
```

Where `$partitionLabelLinkMap` is an array with your labels as keys and your link as the value.

So in my case

```
        foreach ($users as $user) {
            $top[$user->name] = $user->total;
            $partitionLabelLinkMap[$user->name] = sprintf('/nova/resources/users/%d', $user->id);
        }
```


And voila, works like a charm.

To be clear I didn't check if the trend and value metrics still work. Had to do a couple of things to get this package to build on the latest version of node / nova / laravel-mix. I might have broken the trend and value metrics.. but probably not.

**Comment by anderly** [comment]
This is in the just released version 4.0.0. It's probably going to be reworked slightly, but borrowed @vesper8's approach for now.

**Comment by vesper8** [comment]
Hey @anderly,

I'm trying out your new release now and can't get it to work.

When I provide my links to `->links($links);` then for some reason I can't explain the return becomes empty.. there are no errors generated but I can see that the api request returns empty.

Here's my basic partition code

```

        $games = $query
        ->whereNotNull($groupBy)
        ->groupBy($groupBy)
        ->selectRaw(sprintf('count(*) as total, %s as lookup', $groupBy))
        ->orderBy('total', 'desc')
        ->get();

        $top = [];

        foreach ($games as $game) {
            $lookup = $lookupModel::find($game->lookup);
            $name = sprintf('%s - %s', $lookup->eco, $lookup->opening);
            $top[$name] = $game->total;
        }

        return $this->result($top);
```


Here's the same code but I also create `$links`


```


        $games = $query
        ->whereNotNull($groupBy)
        ->groupBy($groupBy)
        ->selectRaw(sprintf('count(*) as total, %s as lookup', $groupBy))
        ->orderBy('total', 'desc')
        ->get();

        $top = [];

        foreach ($games as $game) {
            $lookup = $lookupModel::find($game->lookup);
            $name = sprintf('%s - %s', $lookup->eco, $lookup->opening);
            $top[$name] = $game->total;

            $links[$name] = $lookup->novaLink();
        }

        return $this->result($top)->links($links);
```

The api then returns `{"value":null}`

As a test if I return this `return $this->result($top)->links([]);`

Then I also get `{"value":null}`

Confused because inside `BasePartitionMetric.vue` I see `:href="`${item.label in partitionLinks ? partitionLinks[item.label] : '#'}`"`

If it can't find the label inside the partitionLinks array then it should just fallback to `#` so I don't understand why providing links, whether they be malformed or not, results in `{"value":null}`

Anyway I'm sure I'm just doing something wrong.

Any chance you could post a small snippet demonstrating how to correctly provide links to partition metrics please?

Many thanks!

**Comment by anderly** [comment]
Hi all, the [readme](../../master/README.md#customizing-partition-links) has been updated with usage documentation on how to customize partition links. In short, it behaves very similar to [customizing partition labels](https://nova.laravel.com/docs/4.0/metrics/defining-metrics.html#customizing-partition-labels).

You may still want the partition metric card title to have a simple link and that is still supported, but now you may also provide a Closure callback to the new `link` method to customize the partition metric links.

**Comment by vesper8** [comment]
Thanks. I got it working now. In my case, I'm building up the content for my partition metrics manually, I mean, rather than mapping them to a resource directly, so the most convenient way is still to do it like I am doing it above.

But since your new `link` method requires a closure, I was able to get it working this way:

```

        return $this->result($top)
            ->link(function ($value) use ($links) {
                return $links[$value];
            });
```

**Comment by anderly** [comment]
@vesper8,

Great to hear. Decided to follow the approach Nova takes with customizing labels by using the Closure because you have full control by building it up as you go with a route and params, etc. or by using your own map array like in your example.

Let me know how it goes and if any issues come up.

Thanks!

**Comment by anderly** [comment]
@vesper8,

Just a heads up that you can shorten yours a bit using arrow functions like so:

```php
return $this->result($top)
    ->link(fn ($value) => $links[$value]});
```
